#-------------------------------------------------------------
# Manifest File to create Deployment with Labels and AutoScaling
#
# Copyleft (c) by Nick Burakovets
#-------------------------------------------------------------
---
apiVersion : apps/v1
kind: Deployment

metadata:
  name: {{ .Release.Name }}-deployment-autoscaling   
  
  # Данный метод замещения названия помогает нам использовать один и тот же манифест но с разными параметрами в values
  
  labels:
    app  : {{ .Release.Name }}-application
    env  : prod
    owner: NickBurakovets
spec:
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:

      containers:
        - name : {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          
          # Так же используем имидж из values, при необходимости можно изменить в values
          
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta1

# Подключаем ХПА с требованиями по цпу и памяти

kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: {{ .Release.Name }}-deployment-autoscaling

  # По требованиям ставим максимальное кол-во подов на 4 (мин 2 оставляю на случай если 1 упадёт, и пока восстановится, 1 "под" запасной останется)
  # Если нагрузка будет невысокой, используется только 2 ПОДа (для отказоустойчивости) и автоматически добавляются ПОДы если нагрузка вырастет

  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:

      # Устанавливаем среднее значение употребления цпу

      name: cpu
      targetAverageUtilization: 0.1
  - type: Resource
    resource:

      # Устанавливаем среднее значение потребления памяти

      name: memory
      targetAverageUtilization: 128M
